<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLoginFree
 * @copyright   Copyright (c) 2015 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php
$helper = $this->helper('Plumrocket\SocialLoginFree\Helper\Data');
if( ($image = $helper->getPhotoPath(false)) && $helper->photoEnabled() ): ?>
<li class="pslogin-welcome-msg">
    <img src="<?php echo $image; ?>" />
</li>
<?php endif; ?>
